name: 'UI Tests'

on:
  workflow_dispatch:

jobs:
  user-flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: convertPheno_client
          config-file: cypress/cfg.json
          start: pnpm run dev
